### ISSUE TITLE
1.19.2 update

### ISSUE THREAD

**Issue by thetrooper2281337** [maxsupermanhd/meteor-villager-roller#14]
update to 1.19.1 or 1.19.2

**Comment by maxsupermanhd** [comment]
Meteor is not on 1.19.2, Will update to 1.19.1 shortly

**Comment by thetrooper2281337** [comment]
спс) лучший аддон

**Comment by maxsupermanhd** [comment]
Meteor's maven is down, feel free to ping me whenever it will be up so I can build damn thing (https://status.meteorclient.com/)

**Comment by thetrooper2281337** [comment]
hey. I'm sorry to trouble you, but meteor client on 1.19.2 now. can u update please? i see u already updated to 1.19.1
