### ISSUE TITLE
Where are the artifacts? 

### ISSUE THREAD

**Issue by Bluscream** [maxsupermanhd/meteor-villager-roller#3]
Every build run is empty and there are no releases

**Comment by maxsupermanhd** [comment]
https://github.com/maxsupermanhd/meteor-villager-roller/releases
Use dev builds

**Comment by Bluscream** [comment]
Ahh, can you remove the pre-release flag? So they're actual shown on the repo page

**Comment by maxsupermanhd** [comment]
I think I will just make releases once in a while
