### ISSUE TITLE
villager roller crashes game

### ISSUE THREAD

**Issue by ProxtosScorn** [maxsupermanhd/meteor-villager-roller#36]
after villager is selected the game crashes

**Comment by Big-Iron-Cheems** [comment]
If you're going to report a crash, have the decency to at least provide the full crash log too.
Can't do anything without it.

**Comment by maxsupermanhd** [comment]
Invalid as no crash report provided within 12 hours. Reopen with crash report if issue exists.

**Comment by maxsupermanhd** [comment]
Exit code -1 does not contain any information that you can use to debug issue within the program. You need a crash report, find it, if you can't then we can't help you nor anyone else can.

**Comment by ProxtosScorn** [comment]
found report


---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-05-07 10:36:06
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.player.InstaMine.isActive()" because "im" is null
	at meteordevelopment.meteorclient.utils.world.BlockUtils.breakBlock(BlockUtils.java:230)
	at maxsuperman.addons.roller.modules.VillagerRoller.onTick(VillagerRoller.java:662)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:53)
	at net.minecraft.class_310.handler$cgj001$meteor-client$onPreTick(class_310.java:25329)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.meteorclient.utils.world.BlockUtils.breakBlock(BlockUtils.java:230)
	at maxsuperman.addons.roller.modules.VillagerRoller.onTick(VillagerRoller.java:662)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:53)
	at net.minecraft.class_310.handler$cgj001$meteor-client$onPreTick(class_310.java:25329)

-- Uptime --
Details:
	JVM uptime: 867.332s
	Wall uptime: 769.637s
	High-res time: 749.487s
	Client ticks: 13579 ticks / 678.950s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Proxtos'/275, l='ClientLevel', x=287.45, y=71.00, z=1993.70]]
	Chunk stats: 1024, 145
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,97,-48), Section: (at 0,1,0 in -1,6,-3; chunk contains blocks -16,-64,-48 to -1,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 7038214 game time, 8686380 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
	Tracked entity count: 126

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, file/Bare+Bones+1.20, fabric, appleskin, armortrimitemfix, autoclicker-fabric, betterf3, betterpingdisplay, caffeineconfig, capes, chat_heads, citresewn, citresewn-defaults, cloth-config, dynamic_fps, easiervillagertrading, eatinganimationid, entityculling, exordium, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fullbrightnesstoggle, gbfabrictools, healthindicator, horsestatsvanilla, immediatelyfast, indium, inventoryhud, itemscroller, jankson, lambdynlights, lazydfu, libgui, litematica, lithium, malilib, marlows-crystal-optimizer, meteor-client, meteor-litematica-printer, meteor-rejects, meteor-villager-roller, meteorplus, midnightlib, minecraftcapes, minihud, modernfix, modmenu, numbyhack, pride, reeses-sodium-options, replaymod, seedcrackerx-api, shulkerboxtooltip, sodium, sodium-extra, spruceui, starlight, totemcounter, tweakeroo, ukulib, walksycrystaloptimizer, yet_another_config_lib_v3, zoomify, minecraft:supporteatinganimation, file/visual cauldron state, file/biblicaltou, file/§6tipped-arrow, file/200IQ Big Brain GUI 1.20, file/Obscuria's-Tools-1.19, file/Obscuria's Halloween Netherite, file/LowOnFire_1.20.1, file/1-20-ore-outline, file/improved-effect-icons-beatso, file/Particles+V.1.3, file/Armor Points on Armor Name - Ekuzen, file/Better_Armor_Trims_v1.0, file/fancy-glint, file/xali's Potions v1.0, file/xali's Enchanted Books v0.12.0, file/Shield Corrections [Colored], file/Hunger Points on Food Name - Ekuzen, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 878868352 bytes (838 MiB) / 1342177280 bytes (1280 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-1235U
	Identifier: Intel64 Family 6 Model 154 Stepping 4
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x46a8
	Graphics card #0 versionInfo: DriverVersion=31.0.101.4255
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31064.22
	Virtual memory used (MB): 25860.40
	Swap memory total (MB): 14986.16
	Swap memory used (MB): 2367.59
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 2.5.1+mc1.20.3
		armortrimitemfix: Armor Trim Item Fix 1.0.2
		autoclicker-fabric: Auto Clicker 84.0.0
		baritone-meteor: Baritone 1.20.4-SNAPSHOT
			dev_babbaj_nether-pathfinder: nether-pathfinder 1.4.1
		betterf3: BetterF3 9.0.2
		betterpingdisplay: Better Ping Display 1.1.1
		capes: Capes 1.5.3+1.20.2
		chat_heads: Chat Heads 0.10.32
		citresewn: CIT Resewn 1.1.4+1.20.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.4+1.20.4
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.40
		customparticles: Custom Totem Particles 2.2
		dynamic_fps: Dynamic FPS 3.4.2
		easiervillagertrading: EasierVillagerTrading 1.20.4-fabric0.91.2-1.5.4
			gbfabrictools: GBfabrictools 1.4+1.20
		eatinganimationid: Eating Animation 1.20+1.9.61
		entityculling: EntityCulling 1.6.4
		exordium: Exordium 1.2.1
		fabric-api: Fabric API 0.96.11+1.20.4
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.15+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.4+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.4+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.1+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.26+58f8c0124f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.9+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.65+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.14+080016e44f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.19+58f8c0124f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.53+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.1+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.56+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.0+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.20+df798a894f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.11+eb30349a4f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 6.0.3
		fullbrightnesstoggle: Full Brightness Toggle 4.0
		healthindicator: HealthIndicator 1.3.0+mc1.20.3
		horsestatsvanilla: Horse Stats Vanilla 4.5.0
			libgui: LibGui 9.0.0+1.20.2
				jankson: Jankson 6.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		immediatelyfast: ImmediatelyFast 1.2.11+1.20.4
			net_lenni0451_reflect: Reflect 1.3.2
		indium: Indium 1.0.30+mc1.20.4
		inventoryhud: Inventory HUD + 3.4.19
		itemscroller: Item Scroller 0.22.0
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.4+1.20.4
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.3+1.20.2
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.17.2
		lithium: Lithium 0.12.1
		malilib: MaLiLib 0.18.1
		marlows-crystal-optimizer: Flash Crystal Optimizer 1.0.0
		meteor-client: Meteor Client 0.5.6-2044
		meteor-litematica-printer: Meteor Litematica Printer 1.3
		meteor-rejects: Meteor Rejects 0.3
			seedcrackerx-api: SeedCrackerX API 2.10.1
		meteor-villager-roller: Meteor Villager Roller 1.4.4+mc1.20.4-rev.aec87b6
		meteorplus: Meteor Plus 1.0.6
		minecraft: Minecraft 1.20.4
		minecraftcapes: MinecraftCapes 12.3.7
		minihud: MiniHUD 0.30.2
		modelfix: Model Gap Fix 1.14
		modernfix: ModernFix 5.16.1+mc1.20.4
		modmenu: Mod Menu 9.0.0
		mousetweaks: Mouse Tweaks 2.26
		numbyhack: Numby Hack 2.2
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.4-build.102
		replaymod: Replay Mod 1.20.4-2.6.15
		shulkerboxtooltip: Shulker Box Tooltip 4.0.8+1.20.4
		sodium: Sodium 0.5.8+mc1.20.4
		sodium-extra: Sodium Extra 0.5.4+mc1.20.4-build.116
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		starlight: Starlight 1.1.3+fabric.f5dcd1a
		totemcounter: TotemCounter 1.4.0+mc1.20.3
		tweakeroo: Tweakeroo 0.19.2
		ukulib: ukulib 1.1.2+1.20.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		walksycrystaloptimizer: Walksy Optimizer 1.2.0
			midnightlib: MidnightLib 0.5.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.3.2+1.20.4
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.13.1
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Launched Version: fabric-loader-0.15.7-1.20.4
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Intel(R) Iris(R) Xe Graphics GL version 3.2.0 - Build 31.0.101.4255, Intel
	Window size: 1920x991
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fast
	Render Distance: 5/8 chunks
	Resource Packs: vanilla, file/Bare+Bones+1.20 (incompatible), fabric, appleskin (incompatible), armortrimitemfix (incompatible), autoclicker-fabric, betterf3, betterpingdisplay, caffeineconfig, capes, chat_heads, citresewn, citresewn-defaults, cloth-config, dynamic_fps, easiervillagertrading, eatinganimationid, entityculling, exordium, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fullbrightnesstoggle (incompatible), gbfabrictools, healthindicator, horsestatsvanilla, immediatelyfast, indium, inventoryhud, itemscroller, jankson, lambdynlights, lazydfu, libgui, litematica, lithium, malilib, marlows-crystal-optimizer, meteor-client, meteor-litematica-printer, meteor-rejects, meteor-villager-roller, meteorplus, midnightlib, minecraftcapes (incompatible), minihud, modernfix (incompatible), modmenu, numbyhack, pride, reeses-sodium-options, replaymod (incompatible), seedcrackerx-api, shulkerboxtooltip, sodium, sodium-extra, spruceui, starlight, totemcounter, tweakeroo (incompatible), ukulib, walksycrystaloptimizer, yet_another_config_lib_v3, zoomify, minecraft:supporteatinganimation (incompatible), file/visual cauldron state (incompatible), file/biblicaltou (incompatible), file/§6tipped-arrow, file/200IQ Big Brain GUI 1.20 (incompatible), file/Obscuria's-Tools-1.19 (incompatible), file/Obscuria's Halloween Netherite (incompatible), file/LowOnFire_1.20.1 (incompatible), file/1-20-ore-outline (incompatible), file/improved-effect-icons-beatso (incompatible), file/Particles+V.1.3, file/Armor Points on Armor Name - Ekuzen (incompatible), file/Better_Armor_Trims_v1.0 (incompatible), file/fancy-glint (incompatible), file/xali's Potions v1.0 (incompatible), file/xali's Enchanted Books v0.12.0 (incompatible), file/Shield Corrections [Colored] (incompatible), file/Hunger Points on Food Name - Ekuzen (incompatible)
	Current Language: en_us
	Locale: en_US
	CPU: 12x 12th Gen Intel(R) Core(TM) i5-1235U

-- Meteor Client --

Version: 0.5.6
Dev Build: 2044

[[ Active Modules ]]

[Combat]:
criticals

[Player]:
anti-hunger
middle-click-extra
portals

[Movement]:
fast-climb
no-fall
no-slow
velocity

[Render]:
logout-spots
trajectories

[Misc]:
villager-roller

[Rejects]:
anti-crash
no-jump-delay
vehicle-one-hit

**Comment by maxsupermanhd** [comment]
This is incompatibility between rejects and meteor that is *triggered* by roller and other addons that use BlockUtils.
It was fixed on meteor side, use proper meteor client.

Ref: https://github.com/MeteorDevelopment/meteor-client/issues/4478
