### ISSUE TITLE
Entity interactions on 2b2t

### ISSUE THREAD

**Issue by sebseb7** [maxsupermanhd/meteor-villager-roller#37]
Hi,

it seems that ```mc.interactionManager.interactEntity(mc.player, rollingVillager, Hand.MAIN_HAND);```

https://github.com/maxsupermanhd/meteor-villager-roller/blob/bd1a1a14ebfeefbcfda76d9eb26d2ebe98219ea0/src/main/java/maxsuperman/addons/roller/modules/VillagerRoller.java#L510C12-L510C19

no longer works on 2b2t for some reason.

**Comment by maxsupermanhd** [comment]
Oh yeah, I am aware. A guy reached to me at may 4th and we tried to troubleshoot it but it just seems like server completely ignores the clicks. Funny thing is if you schedule an autoclicker (on os level) it would interact properly.

Unfortunately I don't really get the difference between having an actual click and just executing `interactEntity` so I can't do much. I don't play on 2b but if you have a solution for it you are welcome to create pull requests with your suggestions. Just make sure if it can potentially break stuff for non 2b players put it behind a toggle.

**Comment by sebseb7** [comment]
is there a packet logger I can try compare client difference between "clicks" issued on keypress level and clicks issues indirectly at interactionManager level?

**Comment by maxsupermanhd** [comment]
Sure can, you can use https://github.com/adepierre/SniffCraft and to be honest probably any packet logger will do the job.

**Comment by sebseb7** [comment]
btw. looking at the villger and issuing

```
KeyBinding.setKeyPressed(InputUtil.fromTranslationKey(mc.options.useKey.getBoundKeyTranslationKey()),true);
```

does work in my testing if the viewpoint is static.

**Comment by maxsupermanhd** [comment]
> if the viewpoint is static

Hmm. I did send a test version with randomized delay before interaction to the guy that was troubleshooting with me but it did not work out.

This is very confusing...

btw you can reach me in discord.

**Comment by sebseb7** [comment]
will do tomorrow

**Comment by maxsupermanhd** [comment]
Please try new release, hope it fixes the issue, reopen if issue persists
