### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by UnderQuestion** [maxsupermanhd/meteor-villager-roller#39]
cant choose books to villager find

**Comment by maxsupermanhd** [comment]
You mist be in the world, not in main menu as in 1.21 books are registered into the game on per-world basis. Also provide more details.

**Comment by maxsupermanhd** [comment]
Is server actually running server on version 1.21? Do you use via?

**Comment by maxsupermanhd** [comment]
Then server does not register any enchants, this is to be expected. Partially via's fault since such versions must carry fixed registry of enchantments in that case.

Provide output of `.nbt` while holding bought enchanted book.
