### ISSUE TITLE
I think its 2 here

### ISSUE THREAD

**Issue by FeeNiiX** [maxsupermanhd/meteor-villager-roller#41]
https://github.com/maxsupermanhd/meteor-villager-roller/blob/b67561e7e35155f93950130bbf729cf990a63346/src/main/java/maxsuperman/addons/roller/modules/VillagerRoller.java#L416

Fix --> setOptimal.tooltip = "Set to optimal price (2 + maxLevel * 3) (double if treasure) (if known)";

A Level 5 enchant would be 2 + (5 * 3) = 17 <-- Cheapest Lvl 5 Enchant
Instead of 5 + (5 * 3) = 20

**Comment by maxsupermanhd** [comment]
Good catch, no idea how it happened, in the actual calculation it uses correct 2+3*maxLevel
