### ISSUE TITLE
Idk why but when I do v 1.19 this happens

### ISSUE THREAD

**Issue by Sasuke1216** [maxsupermanhd/meteor-villager-roller#7]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Meteor Villager Roller' (meteor-villager-roller) 1.3+mc1.18.2-rev.3d6f694 with any version that is compatible with:
		 - minecraft 1.19
Unmet dependency listing:
	 - Mod 'Meteor Villager Roller' (meteor-villager-roller) 1.3+mc1.18.2-rev.3d6f694 requires version 1.18.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by maxsupermanhd** [comment]
How about you try to read what you download, there are 2 versions attached to release, one for 1.18.2 and one for 1.19, it is stated in the filename.
